# Generated by Django 4.1.1 on 2022-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_action_alter_item_mark_item_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='translation',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
