# Generated by Django 4.1.1 on 2022-11-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='item',
            name='actions',
            field=models.ManyToManyField(to='orders.action', verbose_name='Produkcja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Srebrny', 'Srebrny'), ('Złoty', 'Złoty'), ('Biały', 'Biały'), ('Czarny', 'Czarny'), ('Bezbarwny', 'Bezbarwny'), ('Niestandardowy', 'Niestandardowy')], max_length=50, verbose_name='Kolor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Głębokość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Opis projektu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, choices=[('Zewnętrzne', 'Zewnętrzne'), ('Wewnętrzne', 'Wewnętrzne')], default='Zewnętrzne', max_length=30, null=True, verbose_name='Wymiary'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fastening',
            field=models.CharField(choices=[('Pins', 'Pins'), ('Magnes', 'Magnes'), ('Klej', 'Klej'), ('Otwór', 'Otwór'), ('Bez', 'Bez'), ('Niestandardowy', 'Niestandardowy')], max_length=30, verbose_name='Mocowanie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.IntegerField(verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hole',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Otwór'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mark',
            field=models.CharField(choices=[('Druk', 'Druk'), ('Grawer', 'Grawer'), ('Folia', 'Folia'), ('Naklejka', 'Naklejka'), ('Outsourcing', 'Outsourcing'), ('Bez', 'Bez'), ('Niestandardowy', 'Niestandardowy')], max_length=50, verbose_name='Znakowanie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[('Aluminium', 'Aluminium'), ('Laminat', 'Laminat'), ('Dibond', 'Dibond'), ('Poliwęglan', 'Poliwęglan'), ('Pleksi', 'Pleksi'), ('Niestandardowy', 'Niestandardowy')], max_length=50, verbose_name='Materiał'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('Gotowce', 'Gotowce'), ('Identyfikatory', 'Identyfikatory'), ('Numerki', 'Numerki'), ('Osłony', 'Osłony'), ('Dyplomy', 'Dyplomy'), ('Szablon', 'Szablon'), ('Pleksi', 'Pleksi'), ('Pojemnik', 'Pojemnik'), ('Tablica', 'Tablica'), ('Statuetki', 'Statuetki'), ('Tabliczki', 'Tabliczki'), ('Litery', 'Litery')], max_length=30, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rounding',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zaokrąglenie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thickness',
            field=models.CharField(choices=[('0,5', '0,5'), ('0,8', '0,8'), ('1,6', '1,6'), ('2', '2'), ('3', '3'), ('5', '5'), ('Inne', 'Inne')], max_length=10, verbose_name='Grubość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.IntegerField(verbose_name='Szerokość'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.EmailField(max_length=260, verbose_name='klient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='designer',
            field=models.CharField(choices=[('Miki', 'Miki'), ('Ola', 'Ola')], default='Miki', max_length=20, verbose_name='grafik'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.CharField(choices=[('Marek', 'Marek'), ('Natalia', 'Natalia'), ('Joanna', 'Joanna')], max_length=20, verbose_name='handlowiec'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Wycena', 'Wycena'), ('Nowe', 'Nowe'), ('Pilne', 'Pilne'), ('Rysowane', 'Rysowane'), ('Niekompletne', 'Niekompletne'), ('Zaprojektowane', 'Zaprojektowane'), ('Oceniane', 'Oceniane'), ('Poprawka', 'Poprawka'), ('Zaakceptowane', 'Zaakceptowane'), ('Produkcja', 'Produkcja'), ('Zapakowane', 'Zapakowane'), ('Wysłane', 'Wysłane')], default='Wycena', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='klient')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('zip_code', models.CharField(max_length=6, verbose_name='zip code')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('shipment_date', models.DateField(verbose_name='shipment date')),
                ('shipment_comment', models.TextField(blank=True, verbose_name='shipment comment')),
                ('phone_number', models.CharField(max_length=12, verbose_name='phone number')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
