# Generated by Django 4.1.1 on 2022-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_action_options_alter_comment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, verbose_name='miasto'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='numer telefonu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipment_comment',
            field=models.TextField(blank=True, verbose_name='uwaga do wysyłki'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shipment_date',
            field=models.DateField(verbose_name='data wysyłki'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='ulica'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='komentarz'),
        ),
        migrations.AlterField(
            model_name='item',
            name='actions',
            field=models.ManyToManyField(to='orders.action', verbose_name='Akcja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('Srebrny', 'Srebrny'), ('Złoty', 'Złoty'), ('Biały', 'Biały'), ('Czarny', 'Czarny'), ('Bezbarwny', 'Bezbarwny'), ('Niestandardowy', 'Niestandardowy')], max_length=50, verbose_name='kolor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='głębokość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='opis projektu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, choices=[('Zewnętrzne', 'Zewnętrzne'), ('Wewnętrzne', 'Wewnętrzne')], default='Zewnętrzne', max_length=30, null=True, verbose_name='wymiary'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fastening',
            field=models.CharField(choices=[('Pins', 'Pins'), ('Magnes', 'Magnes'), ('Klej', 'Klej'), ('Otwór', 'Otwór'), ('Bez', 'Bez'), ('Niestandardowy', 'Niestandardowy')], max_length=30, verbose_name='mocowanie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.IntegerField(verbose_name='wysokość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hole',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='otwór'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mark',
            field=models.CharField(choices=[('Druk', 'Druk'), ('Grawer', 'Grawer'), ('Folia', 'Folia'), ('Naklejka', 'Naklejka'), ('Outsourcing', 'Outsourcing'), ('Bez', 'Bez'), ('Niestandardowy', 'Niestandardowy')], max_length=50, verbose_name='znakowanie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[('Aluminium', 'Aluminium'), ('Laminat', 'Laminat'), ('Dibond', 'Dibond'), ('Poliwęglan', 'Poliwęglan'), ('Pleksi', 'Pleksi'), ('Niestandardowy', 'Niestandardowy')], max_length=50, verbose_name='materiał'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('Gotowce', 'Gotowce'), ('Identyfikatory', 'Identyfikatory'), ('Numerki', 'Numerki'), ('Osłony', 'Osłony'), ('Dyplomy', 'Dyplomy'), ('Szablon', 'Szablon'), ('Pleksi', 'Pleksi'), ('Pojemnik', 'Pojemnik'), ('Tablica', 'Tablica'), ('Statuetki', 'Statuetki'), ('Tabliczki', 'Tabliczki'), ('Litery', 'Litery')], max_length=30, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='ilość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rounding',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='zaokrąglenie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thickness',
            field=models.CharField(choices=[('0,5', '0,5'), ('0,8', '0,8'), ('1,6', '1,6'), ('2', '2'), ('3', '3'), ('5', '5'), ('Inne', 'Inne')], max_length=10, verbose_name='grubość'),
        ),
    ]
